apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: NAME
  namespace: NAMESPACE
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'EMAIL_ID'
    privateKeySecretRef:
      name: NAME
    solvers:
    - http01:
        ingress:
          class: nginx
